spring:
  application:
    name: online-chat
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: chengxiang
    url: jdbc:mysql://120.26.213.250:3306/chat?serverTimeZone=Shanghai
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
  mail:
    host: smtp.qq.com
    username: 1923136366@qq.com
    password: hsknhzwnharbcibj

  redis:
    host: 120.26.213.250
    port: 6379

server:
  port: 3333

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl







